[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maaz Amir", email = "amirmaaz16@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.141.1",
    "langchain>=1.4.0",
    "langchain-google-genai>=4.4.0",
    "langchain-openai>=1.6.1",
    "psycopg2-binary>=2.9.12",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[tool.uv.build-backend]
module-name = ["core", "db", "models", "routers", "schemas"]

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
